// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://ynslzmpfhmoghvcacwzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inluc2x6bXBmaG1vZ2h2Y2Fjd3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDIzMzcsImV4cCI6MjA2MTMxODMzN30.h5HZOI-NvdDcHYww36g8DpMYnWZlGwORxexAR-FsCWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);